config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :produtos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:quantA, :quantB, :valA, :valB, :total)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :valor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pedidos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido,  id:'formPedido', local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantA %>
    <%= form.number_field :quantA, :min => '0', :value => '0'  %>
  </div>

  <div class="field">
    <%= form.label :quantB %>
    <%= form.number_field :quantB, :min => '0', :value => '0'  %>
  </div>

    <% produtos = Produto.first(2)%>

  <div class="field">
    <%= form.label :valA %>
    <%= form.text_field :valA, :readonly => 'readonly', :value => produtos[0].valor %>
  </div>

  <div class="field">
    <%= form.label :valB %>
    <%= form.text_field :valB, :readonly => 'readonly', :value => produtos[1].valor  %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total, :readonly => 'readonly', :value => '0' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Show', @pedido %> |

<script type="text/javascript">
  var formPedido;

  formPedido = void 0;

  formPedido = document.forms['formPedido'];

  formPedido.pedido_quantA.value = 0;

  formPedido.pedido_quantB.value = 0;

  formPedido.pedido_quantA.onchange = function() {
    formPedido.pedido_total.value = parseInt(formPedido.pedido_quantA.value) * parseInt(formPedido.pedido_valA.value) + parseInt(formPedido.pedido_quantB.value) * parseInt(formPedido.pedido_valB.value);
  };

  formPedido.pedido_quantB.onchange = function() {
    formPedido.pedido_total.value = parseInt(formPedido.pedido_quantA.value) * parseInt(formPedido.pedido_valA.value) + parseInt(formPedido.pedido_quantB.value) * parseInt(formPedido.pedido_valB.value);
  };
</script>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Quanta</th>
      <th>Quantb</th>
      <th>Vala</th>
      <th>Valb</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.quantA %></td>
        <td><%= pedido.quantB %></td>
        <td><%= pedido.valA %></td>
        <td><%= pedido.valB %></td>
        <td><%= pedido.total %></td>
        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New Pedido</h1>

<%= render 'form', pedido: @pedido %>
<script type="text/javascript">
  var formPedido;

  formPedido = void 0;

  formPedido = document.forms['formPedido'];

  formPedido.pedido_quantA.value = 0;

  formPedido.pedido_quantB.value = 0;

  formPedido.pedido_quantA.onchange = function() {
    formPedido.pedido_total.value = parseInt(formPedido.pedido_quantA.value) * parseInt(formPedido.pedido_valA.value) + parseInt(formPedido.pedido_quantB.value) * parseInt(formPedido.pedido_valB.value);
  };

  formPedido.pedido_quantB.onchange = function() {
    formPedido.pedido_total.value = parseInt(formPedido.pedido_quantA.value) * parseInt(formPedido.pedido_valA.value) + parseInt(formPedido.pedido_quantB.value) * parseInt(formPedido.pedido_valB.value);
  };
</script>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quanta:</strong>
  <%= @pedido.quantA %>
</p>

<p>
  <strong>Quantb:</strong>
  <%= @pedido.quantB %>
</p>

<p>
  <strong>Vala:</strong>
  <%= @pedido.valA %>
</p>

<p>
  <strong>Valb:</strong>
  <%= @pedido.valB %>
</p>

<p>
  <strong>Total:</strong>
  <%= @pedido.total %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.valor %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>